name: Test
on:
  pull_request:
    branches:
    - master
jobs:
  job-test:
    name: Run unit tests
    runs-on: macOS-latest    
    steps:
    - uses: actions/checkout@v1
    - name: Install needed software
      run: |
        gem install xcpretty 
        gem install bundler:1.17.2
        brew install swiftlint
        brew uninstall carthage
        brew tap nsoperations/formulas
        brew install nsoperations/formulas/carthage 
    - name: Cache
      uses: actions/cache@v1
      with:
        path: Carthage
        key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}-carthage-
    - name: Carthage bootstrap
      run: carthage bootstrap --platform iOS --cache-builds
      env: 
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Force XCode 11.4
      run: sudo xcode-select -switch /Applications/Xcode_11.4.app
    #- name: Testing Swift package
    #  run: exec ./.github/scripts/test_swift_package.sh
    - name: Testing iOS app
      run: exec ./.github/scripts/test_app.sh
    - name: Danger Swift
      uses: danger/swift@2.0.3
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.1.0
